<h1>Página Sobre Nós</h1>

<?php
foreach ($this->view->dados as $key => $informacoes) {
?>
    
    <h1> <?= $informacoes['titulo'] ?></h1>
    <br/>
    <p> > <?= $informacoes['descricao'] ?></p>
    <hr>
<?php 
}
?>

    






<?php
/*
foreach ($this->view->dados as $key => $informacoes) {
    echo"<hr>";
    echo $informacoes['titulo']." - ".$informacoes['descricao'];
    echo"<br>";
    echo"<hr>";
}
*/

?>